### ISSUE TITLE
[feature] customization pname

### ISSUE THREAD

**Issue by Freed-Wu** [berberman/nvfetcher#101]
Can it allow users customize pname? That is:

```toml
[qq-nt-x86_64-linux]
pname = "qq-nt"
src.manual = "3.1.2_12912"
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_amd64.deb"

[qq-nt-aarch64-linux]
pname = "qq-nt"
src.manual = "3.1.2_12912"
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_arm64.deb"
```

will generate

```nix
# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  qq-nt-aarch64-linux = {
    pname = "qq-nt";
    version = "3.1.2_12912";
    src = fetchurl {
      url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_arm64.deb";
      sha256 = "sha256-5n4T0mlfEh9/84wUYiH437R95Qz6/SKDq/AK6baiW24=";
    };
  };
  qq-nt-x86_64-linux = {
    pname = "qq-nt";
    version = "3.1.2_12912";
    src = fetchurl {
      url = "https://dldir1.qq.com/qqfile/qq/QQNT/80d33f88/linuxqq_3.1.2-12912_amd64.deb";
      sha256 = "sha256-F+zIHqYWKiCHYNJZ5hRw0rzltizjuqhVxbpzQGagoZ0=";
    };
  };
}
```
