### ISSUE TITLE
git.fetchSubmodules no longer work after #103

### ISSUE THREAD

**Issue by vlaci** [berberman/nvfetcher#104]
After #103, the following config no longer works:

```toml
[wezterm-nightly]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true
cargo_locks = [ "Cargo.lock" ]
```

```console
❯ nix run github:berberman/nvfetcher
nvfetcher: In [wezterm-nightly], unexpected keys found: git.fetchSubmodules
```

When building from the previous version, it works as expected:

```console
❯ nix run github:berberman/nvfetcher/c5ae2cb436a04f4590306589e71638d023a33bd4
# CheckGit
    url: https://github.com/wez/wezterm
    branch:
# FetchGitHub
  owner: wez
  repo: wezterm
  rev: c1f495099ef544eda78546191c0026e88e1fdd62
  deepClone: False
  fetchSubmodules: True
  leaveDotGit: False
# ExtractSrc
  fetcher: FetchGitHub
    owner: wez
    repo: wezterm
    rev: c1f495099ef544eda78546191c0026e88e1fdd62
    deepClone: False
    fetchSubmodules: True
    leaveDotGit: False
  files: [Cargo.lock]
# FetchRustGitDeps
  fetcher: FetchGitHub
    owner: wez
    repo: wezterm
    rev: c1f495099ef544eda78546191c0026e88e1fdd62
    deepClone: False
    fetchSubmodules: True
    leaveDotGit: False
  cargoLock: Cargo.lock
# GetGitCommitDate
  url: https://github.com/wez/wezterm
  rev: c1f495099ef544eda78546191c0026e88e1fdd62
  format:
Changes:
wezterm-nightly: baf9d970816e015bee41ed5eb9186ef7f71c454c → c1f495099ef544eda78546191c0026e88e1fdd62
```
