### ISSUE TITLE
Abnormal Command line generated when calling `nix-prefetch-url`

### ISSUE THREAD

**Issue by MiyakoMeow** [berberman/nvfetcher#138]
- Version: 0.6.2.0
- Def:
```toml
[free-download-manager]
src.webpage = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/"
src.regex = "freedownloadmanager_(.*)_amd64.deb"
fetch.url = "https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_$ver_amd64.deb"
```
Result:
```
 Command line: nix-prefetch-url 'https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_6.28.0.6294_amd64.deb">freedownloadmanager_6.28.0.6294_amd64.deb'
Exit code: 1
Stderr:
error: unable to download 'https://debrepo.freedownloadmanager.org/pool/main/f/freedownloadmanager/freedownloadmanager_6.28.0.6294_amd64.deb">freedownloadmanager_6.28.0.6294_amd64.deb': HTTP error 404
       response body:
       <html>
       <head><title>404 Not Found</title></head>
       <body>
       <center><h1>404 Not Found</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>
```
See: [This workflow run](https://github.com/MiyakoMeow/nur-packages/actions/runs/15977498667/job/45063676197#step:7:60)

**Comment by MiyakoMeow** [comment]
Another def has no problem:
```toml
[beatoraja]
src.webpage = "https://www.mocha-repository.info/download.php"
src.regex = "beatoraja(.*)-modernchic.zip"
fetch.url = "https://www.mocha-repository.info/download/beatoraja$ver-modernchic.zip"
```
