### ISSUE TITLE
Error when fetching from github/git

### ISSUE THREAD

**Issue by Catvert** [berberman/nvfetcher#35]
Hello,

I was using nvfetcher for some time now but recently I'm unable to update my packages because I have this error when I'm trying to `nvfetcher -c sources.toml` : 
```
nvfetcher: Error when running Shake build system:
  at want, called at src/NvFetcher.hs:156:16 in nvfetcher-0.4.0.0-BKtv6RRhdwdHOFnLYLVx6I:NvFetcher
* Depends on: build
  at apply1, called at src/NvFetcher/Core.hs:156:27 in nvfetcher-0.4.0.0-BKtv6RRhdwdHOFnLYLVx6I:NvFetcher.Core
* Depends on: Core ("xmonad-contrib")
  at apply1, called at src/Development/Shake/Internal/Rules/Rerun.hs:41:5 in shake-0.19.6-E45ZCRYKsezD1QxxxfLHmD:Development.Shake.Internal.Rules.Rerun
* Depends on: NvcheckerQ (Git {_vurl = "https://github.com/xmonad/xmonad-contrib", _vbranch = Nothing}) (NvcheckerOptions {_stripPrefix = Nothing, _fromPattern = Nothing, _toPattern = Nothing}) ("xmonad-contrib")
  at error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.8.0:Data.Binary.Get
* Raised the exception:
Data.Binary.Get.runGet at position 48: not enough bytes
```

Here is how I fetch xmonad-contrib : 
```toml
[xmonad-contrib]
src.git = "https://github.com/xmonad/xmonad-contrib"
fetch.git = "https://github.com/xmonad/xmonad-contrib"
```

I've also tried this : 
```toml
[xmonad-contrib]
src.gihub = "xmonad/xmonad-contrib"
fetch.github = "xmonad/xmonad-contrib"
```
but this give me a HTTP 403 forbidden error.

Please note that I have other packages in my sources.toml and that it produces the same problem that xmonad-contrib.
I'm sure this config was working before.

Thanks for your help!
