### ISSUE TITLE
manual git revision

### ISSUE THREAD

**Issue by steveeJ** [berberman/nvfetcher#36]
until i found out otherwise i assumed that the following would pass the value of `src.manual` verbatim to the `rev` argument to `fetchgit`. i thought the following snippet to have this effect:

```toml
[holochain_commit_holochain-0_0_110]
src.manual = "holochain-0.0.110"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"
```

unexpectedly to me, but inline with the nvfetcher documentation, this will check for the latest revision on the default branch of the git repository.

is there a way to configure nvfetcher to make this work for generic git repositories? if not, is there one for github specifically?
