### ISSUE TITLE
feature request: only update selected packages

### ISSUE THREAD

**Issue by steveeJ** [berberman/nvfetcher#37]
it would be great if nvfetcher supported selecting packages to update in a similar fashion as [niv update](https://github.com/nmattia/niv#update) does. 

in comparison to niv it would be great if multiple packages could be named. but if that over-complicates this feature i'd also happily invoke nvfetcher in a loop.

**Comment by berberman** [comment]
> it would be great if nvfetcher supported selecting packages to update in a similar fashion as niv update does.

nvfetcher supports [pinning](https://github.com/berberman/nvfetcher#pinned) a package, so you can specify this in the configuration file to prevent packages from future updates. It wouldn't be hard to add a CLI option to approach the niv style - just consider packages being updated as the only packages which are not pinned in this single run.

> in comparison to niv it would be great if multiple packages could be named. but if that over-complicates this feature i'd also happily invoke nvfetcher in a loop.

I'm not sure what this will look like. Could you give some examples?

**Comment by steveeJ** [comment]
> It wouldn't be hard to add a CLI option to approach the niv style - just consider packages being updated as the only packages which are not pinned in this single run.

this would be great!

> I'm not sure what this will look like. Could you give some examples?

consider this config file:

```toml
[nvfetcher]
fetch.github = "berberman/nvfetcher"
src.git = "https://github.com/berberman/nvfetcher"
src.branch = "master"

[crate2nix]
fetch.github = "kolloch/crate2nix"
src.git = "https://github.com/kolloch/crate2nix"

[nixpkgs]
src.git = "https://github.com/nixos/nixpkgs"
src.branch = "release-21.05"
fetch.github = "nixos/nixpkgs"
```

if the intention was to update the sources for _crate2nix_ and _nixpkgs_ we could match these by providing them on the command line.


### take multiple package names

```sh
nvfetcher build crate2nix nixpkgs
```

### take a single regex
if we felt fancy we could use a regex as a matching pattern for the package names, so we could do this:

```sh
nvfetcher build (crate2nix|nixpkgs)
```

i don't have a strong preference for either. i could imagine the regex approach might be easier to implement than the multiple arguments approach. that said, i'd be happy with a single package argument approach as well and just loop over nvfetcher or run it in parallel. 

either way, thanks for your attention in this issue and your work on nvfetcher! :pray:
