### ISSUE TITLE
feature request: please add support for unpacking tarballs referenced by urls

### ISSUE THREAD

**Issue by steveeJ** [berberman/nvfetcher#52]
the config

```toml
[nixpkgs]
src.cmd = "git ls-remote https://github.com/NixOS/nixpkgs release-21.11 | awk '{ print $1 }'"
fetch.url = "https://github.com/nixos/nixpkgs/archive/$ver.tar.gz"
```

will yield the following generated nix expressions:

```nix
  nixpkgs = {
    pname = "nixpkgs";
    version = "78e106cc97a9396009d78cb448229b40e1854654";
    src = fetchurl {
      url = "https://github.com/nixos/nixpkgs/archive/78e106cc97a9396009d78cb448229b40e1854654.tar.gz";
      sha256 = "sha256-X71ovXUkjT/kEUAZOW8T+oy40Ov3L49j/4stDbXIqCU=";
    };
  };
```

this cannot be imported without unpacking, and `builtins.fetchTarball` does not work on local files which leaves me at an impasse without access to an imported nixpkgs set.

it would be solved by the ability to instruct nvfetcher to use `builtins.fetchTarball` on a URL.
