### ISSUE TITLE
src.github_tag does not pull in the latest tag

### ISSUE THREAD

**Issue by blakat360** [berberman/nvfetcher#88]
The following toml:

```toml
[z]
src.github_tag = "jethrokuan/z"
fetch.github = "jethrokuan/z"
```

pulls in tag 1.1 and not <2.7.0

I have tried passing `src.include_regex = ".*"` but that doesn't change anything
