### ISSUE TITLE
Feature Request: version constraints

### ISSUE THREAD

**Issue by viperML** [berberman/nvfetcher#91]
Hello :wave: 

I thought of having version constraints, so for example nvfetcher doesn't pull an update with breaking changes, only minor. Something along the lines of:

```toml
# nvfetcher.toml
[feeluown]
src.pypi = "feeluown"
fetch.pypi = "feeluown"
version = "^3.8.8"
```
