### ISSUE TITLE
Wrong version pulled from github_tag

### ISSUE THREAD

**Issue by viperML** [berberman/nvfetcher#95]
```toml
[soralog]
src.github_tag = "soramitsu/soralog"
src.version = "v0.1.3"
fetch.github = "soramitsu/soralog"
```

I would expect this to pull the tag `v0.1.3`, but the following is generated:

```json
{
    "soralog": {
        "cargoLocks": null,
        "extract": null,
        "name": "soralog",
        "passthru": null,
        "pinned": false,
        "src": {
            "deepClone": false,
            "fetchSubmodules": false,
            "leaveDotGit": false,
            "name": null,
            "owner": "soramitsu",
            "repo": "soralog",
            "rev": "v0.1.5",
            "sha256": "sha256-zjoBQLknPNlNhEIbu60nIYsEZefqmMDfg9myVsAyMq0=",
            "type": "github"
        },
        "version": "v0.1.5"
    }
}
```

Notice how nvfetcher will use rev 0.1.5, instead of 0.1.3

Using nvfetcher from nixpkgs @ ab1254087f4cdf4af74b552d7fc95175d9bdbb49
